### ISSUE TITLE
从互联网访问HA或是使用https协议不能很好的显示媒体缩略图

### ISSUE THREAD

**Issue by howelljiang** [wizmo2/zidoo-player#14]
![image](https://user-images.githubusercontent.com/1620538/228798506-3e6d28ca-81a9-487a-a19c-9a8de378947f.png)

我家的HomeAssistant同时使用了IPv6和https访问。不能正常显示缩略图。

分析以后发现是跨域和https访问的安全性问题。通过代码里面强制通过media_player_proxy可以正常访问。不知道作者有没有更完善的解决方案。

**Comment by wizmo2** [comment]
"My HomeAssistant uses both IPv6 and https access. Thumbnails do not display correctly. After the analysis, it was found that there were security issues with cross-origin and HTTPS access. Through the code to force the passage media_player_proxy can be accessed normally. I don't know if the author has a more complete solution."

Thank you for the feedback.  I will look into it.

**Comment by wizmo2** [comment]
I'm going to go-ahead and close this as stale.  There has been a fair few updates.  If you are still having issues let me know and I'll reopen
