### ISSUE TITLE
Z9X "Media Browsing Error"

### ISSUE THREAD

**Issue by jgdf42** [wizmo2/zidoo-player#21]
![image](https://github.com/wizmo2/zidoo-player/assets/126440193/c6826b8e-9119-466b-9e84-6e7fa8af743e)
![image](https://github.com/wizmo2/zidoo-player/assets/126440193/3f05af0b-da9f-4ba9-bdfc-e6598b0bd7e1)
![image](https://github.com/wizmo2/zidoo-player/assets/126440193/86424c2a-b0f0-4d38-8d43-3b446c4f9e03)
![image](https://github.com/wizmo2/zidoo-player/assets/126440193/fcfec1d7-54ed-4376-b52c-5bdc1203e9a7)

My card used to show the playing media and allow me to browse to media and automatically play it from the frontend. Now it only allows me to turn the player on or off or see the info for it (doesn't show what is playing?), or change the source app within Zidoo (works and shows all source apps). 

I recently removed all my sources and added a different source (all were SMB shares, but a new drive (**\\sharename\D\**) with the previously used drive letter of a different drive). Not sure if this would have caused it, I also updated Home Assistant recently.

**Comment by wizmo2** [comment]
Can you confirm 
- HA version
- Zidoo Version (HACS)

Please also look at the HA full logs and send errors associated with the player.

It could be the `\` in the drive name.   Hopefully the log will confirm.

**Comment by jgdf42** [comment]
Uninstalled and reinstalled the proper way and it resolved!
