### ISSUE TITLE
[possible bug] Playback syncing makes Unfolded Remote Two extremely laggy

### ISSUE THREAD

**Issue by Sledgehamma** [wizmo2/zidoo-player#24]
Hi wizmo,

when using the latest version of your integration while playback it makes the unfolded remote two extremely laggy. Touch and key input has a huge delay and animations stutter extremely.
While playback the remote shows the playback progress plus the episode image like this:
![Image 2](https://github.com/wizmo2/zidoo-player/assets/19309778/bed34244-7386-4cc3-b850-1c78d327dfd2)
When I stop playback, and therefore no progress syncing appears, everything is back to normal and the remote is responsive.

I tried another HA integration with the player entity and the problem does not occur. 

Let me know what details I should provide so you can have a look into that.

Cheers!

**Comment by wizmo2** [comment]
Its most likely associated with rapid update.  Lovelace is pretty good at only updating the frontend if a state value has actually changed.  Its possible the Unfolded firmware is trying to refresh things on every event.  for example, it maybe downloading and redrawing the backdrop image every update event.  

Did you disable any additional rapid update automations?
Is the lag present if there is no backdrop?

**Comment by Sledgehamma** [comment]
Didn’t see any option to disable rapid update automation. 
correct, no lag when there is no backdrop! Good guess :) 
I’ll report it to the unfolded devs.

**Comment by wizmo2** [comment]
> Didn’t see any option to disable rapid update automation.

If you had previously added a [Rapid Update automation](https://github.com/wizmo2/zidoo-player/blob/main/notes.md#rapid-update) before the last update, then its possible it is trying to update twice a second!  

The latest software  adds this feature and sets the poling time to 1s when powered on, to increase response times.  
Rapid Update is not currently in the Config options, but I could look at adding a custom 'update interval' if its a major issue.

You can turn off Rapid Update manually using 'Settings/Device & services/Zidoo' => 'Device hamburger menu/ System Options/Enable Polling for updates'.  If you do disable it you have to add your own automation with a custom update times.

**Comment by Sledgehamma** [comment]
I hadn't added the Rapid Update automation before. I did now with a polling time of 1s and the issue has gone :)

**Comment by Sledgehamma** [comment]
It seems I spoke too soon. The automation doesnt seen to get always triggered, especially if you pause a video.
And now it seems laggy (although not as worse as before) even when set to 1s.

**Comment by wizmo2** [comment]
Yeah, I was surprised it made a difference.  The only thing you can do with this is to slow the update down.  for example, every 5s.

**Comment by wizmo2** [comment]
I believe this was resolved by a Unfolded.  I'm going to close this for now.
